# Generated by Django 5.0.7 on 2024-07-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntradaJournal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("fecha", models.DateField()),
                ("contenido", models.TextField()),
                (
                    "imagen_perfume",
                    models.ImageField(default="default.jpg", upload_to="journal/"),
                ),
            ],
        ),
    ]
