# Generated by Django 5.0.7 on 2024-07-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0002_entradajournal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entradajournal",
            name="imagen_perfume",
            field=models.ImageField(upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="entradajournal",
            name="titulo",
            field=models.CharField(max_length=200),
        ),
    ]
